### ISSUE TITLE
We should prefer ruamel.yaml over PyYAML

### ISSUE THREAD

**Issue by bryanwweber** [Niemeyer-Research-Group/ChemKED#3]
PyYAML appears to be dead: https://bitbucket.org/xi/pyyaml/issues/59/has-this-project-been-abandoned

ruamel.yaml https://yaml.readthedocs.io/en/latest/ is updated and supports YAML 1.2

I have put in import check into the validation module, in case (for some reason) someone must use PyYAML, so if we need to `import yaml` anywhere else in the package, we should do `from .validation import yaml`. There is a conda package for ruamel.yaml (not sure if its official or conda-forge).

**Comment by kyleniemeyer** [comment]
Got it—I was wondering why you introduced `ruamel.yaml`. I just replaced the other instances of `yaml` with `from .validation import yaml` in the `doi-validator` branch via 37ea2c506d677dd9f253f835ec42e15088add880

**Comment by kyleniemeyer** [comment]
Got it—I was wondering why you introduced `ruamel.yaml`. I just replaced the other instances of `yaml` with `from .validation import yaml` in the `doi-validator` branch via 37ea2c506d677dd9f253f835ec42e15088add880

**Comment by bryanwweber** [comment]
This is handled now, right? I'm going to close, feel free to reopen.
